import { useMemo, useState } from "react";
import { Check, Copy, Edit3, Percent, Plus, Save, Search, Tag, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

type CouponForm = { id?: number; code: string; discountPercent: number; usageLimit: number | null; minPurchase: number; validUntil: string; active: number };
const emptyCoupon: CouponForm = { code: "", discountPercent: 10, usageLimit: null, minPurchase: 0, validUntil: "", active: 1 };

export function AdminCouponsSection() {
  const utils = trpc.useUtils();
  const couponsQuery = trpc.coupons.adminList.useQuery();
  const saveMutation = trpc.coupons.save.useMutation({ onSuccess: async () => { toast.success("Cupom guardado com sucesso."); setEditing(null); await utils.coupons.adminList.invalidate(); }, onError: (error) => toast.error(error.message || "Não foi possível guardar o cupom.") });
  const toggleMutation = trpc.coupons.toggle.useMutation({ onSuccess: async () => { await utils.coupons.adminList.invalidate(); toast.success("Estado do cupom atualizado."); }, onError: (error) => toast.error(error.message || "Não foi possível atualizar o cupom.") });
  const removeMutation = trpc.coupons.remove.useMutation({ onSuccess: async () => { await utils.coupons.adminList.invalidate(); toast.success("Cupom removido."); }, onError: (error) => toast.error(error.message || "Não foi possível remover o cupom.") });
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<CouponForm | null>(null);
  const coupons = couponsQuery.data ?? [];
  const filtered = useMemo(() => coupons.filter((coupon) => coupon.code.toLowerCase().includes(query.trim().toLowerCase())), [coupons, query]);
  const activeCount = coupons.filter((coupon) => coupon.active === 1).length;
  const totalUses = coupons.reduce((sum, coupon) => sum + Number(coupon.timesUsed ?? 0), 0);
  const startEdit = (coupon?: typeof coupons[number]) => setEditing(coupon ? { id: coupon.id, code: coupon.code, discountPercent: Number(coupon.discountPercent), usageLimit: coupon.usageLimit, minPurchase: Number(coupon.minPurchase ?? 0), validUntil: coupon.validUntil ? new Date(coupon.validUntil).toISOString().slice(0, 16) : "", active: coupon.active } : { ...emptyCoupon });
  const update = (key: keyof CouponForm, value: string | number | null) => setEditing((current) => current ? { ...current, [key]: value } : current);
  const save = () => { if (!editing) return; saveMutation.mutate({ ...editing, code: editing.code.toUpperCase(), validUntil: editing.validUntil ? new Date(editing.validUntil).toISOString() : null }); };

  return <section className="admin-content admin-editorial-page admin-coupons-page">
    <div className="admin-editorial-hero"><div><span className="section-kicker">CRESCIMENTO · OFERTAS</span><h2 className="content-title">Cupons</h2><p className="content-subtitle">Crie incentivos com regras claras, acompanhe utilizações e mantenha cada oferta sob controlo.</p></div><Button className="admin-primary-action" onClick={() => startEdit()}><Plus size={16} /> Criar cupom</Button></div>
    <div className="admin-editorial-metrics"><div className="admin-editorial-metric"><Tag size={18} /><span>Cupons ativos</span><strong>{activeCount}</strong></div><div className="admin-editorial-metric"><Percent size={18} /><span>Utilizações</span><strong>{totalUses}</strong></div><div className="admin-editorial-metric"><Check size={18} /><span>Taxa monitorizada</span><strong>{coupons.length ? "100%" : "—"}</strong></div></div>
    <div className="content-toolbar admin-editorial-toolbar"><div className="search-box"><Search size={15} /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar código de cupom" /></div><span className="inventory-count">{filtered.length} {filtered.length === 1 ? "cupom" : "cupons"}</span></div>
    {couponsQuery.isLoading ? <div className="admin-panel admin-empty-state"><span className="admin-loading-mark" />A carregar cupons persistidos...</div> : filtered.length === 0 ? <div className="admin-panel admin-empty-state"><Tag size={28} /><strong>{query ? "Nenhum cupom encontrado" : "Ainda não existem cupons"}</strong><span>{query ? "Experimente outro código." : "Crie o primeiro cupom para começar a acompanhar ofertas reais."}</span>{query ? <Button variant="outline" onClick={() => setQuery("")}>Limpar busca</Button> : <Button variant="outline" onClick={() => startEdit()}>Criar primeiro cupom</Button>}</div> : <div className="admin-coupon-grid-premium">{filtered.map((coupon) => <article className={`admin-coupon-card-premium ${coupon.active ? "is-active" : "is-inactive"}`} key={coupon.id}><div className="admin-coupon-card-top"><div className="admin-coupon-emblem"><Tag size={18} /></div><span className={`status-pill ${coupon.active ? "success" : "warning"}`}>{coupon.active ? "Ativo" : "Inativo"}</span></div><div className="admin-coupon-code-row"><strong>{coupon.code}</strong><button type="button" aria-label="Copiar código" title="Copiar código" onClick={() => { void navigator.clipboard?.writeText(coupon.code); toast.success("Código copiado."); }}><Copy size={14} /></button></div><p className="admin-coupon-discount">{Number(coupon.discountPercent).toLocaleString("pt-BR")} <small>% OFF</small></p><div className="admin-coupon-details"><span>Usos <strong>{coupon.timesUsed ?? 0}{coupon.usageLimit ? ` / ${coupon.usageLimit}` : " / ilimitado"}</strong></span><span>Compra mínima <strong>{Number(coupon.minPurchase ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</strong></span><span>Validade <strong>{coupon.validUntil ? new Date(coupon.validUntil).toLocaleDateString("pt-BR") : "Sem prazo"}</strong></span></div><div className="admin-coupon-actions"><button type="button" className="admin-inline-action" onClick={() => startEdit(coupon)}><Edit3 size={14} /> Editar</button><button type="button" className="admin-inline-action" onClick={() => toggleMutation.mutate({ id: coupon.id, active: coupon.active ? 0 : 1 })}>{coupon.active ? "Desativar" : "Ativar"}</button><button type="button" className="admin-inline-action danger" onClick={() => removeMutation.mutate({ id: coupon.id })}><Trash2 size={14} /></button></div></article>)}</div>}
    {editing && <div className="admin-modal-overlay"><div className="admin-panel admin-modal admin-editorial-modal"><div className="panel-heading"><div><span className="section-kicker">EDITOR DE OFERTA</span><h3>{editing.id ? "Editar cupom" : "Novo cupom"}</h3></div><button type="button" className="admin-modal-close" aria-label="Fechar" onClick={() => setEditing(null)}><X size={18} /></button></div><div className="admin-editorial-form-grid"><label>Código<Input value={editing.code} onChange={(event) => update("code", event.target.value.toUpperCase())} placeholder="ERAS10" /></label><label>Desconto (%)<Input type="number" min="0.01" max="100" step="0.01" value={editing.discountPercent} onChange={(event) => update("discountPercent", Number(event.target.value))} /></label><label>Limite de usos<Input type="number" min="1" value={editing.usageLimit ?? ""} onChange={(event) => update("usageLimit", event.target.value ? Number(event.target.value) : null)} placeholder="Ilimitado" /></label><label>Compra mínima<Input type="number" min="0" step="0.01" value={editing.minPurchase} onChange={(event) => update("minPurchase", Number(event.target.value))} /></label><label>Válido até<Input type="datetime-local" value={editing.validUntil} onChange={(event) => update("validUntil", event.target.value)} /></label><label className="admin-toggle-field"><input type="checkbox" checked={editing.active === 1} onChange={(event) => update("active", event.target.checked ? 1 : 0)} /><span>Publicar imediatamente</span></label></div><div className="admin-editorial-modal-footer"><span className="admin-editorial-note">A validação do desconto utiliza as regras reais do checkout.</span><Button variant="outline" onClick={() => setEditing(null)}>Cancelar</Button><Button className="admin-primary-action" disabled={saveMutation.isPending || !editing.code.trim()} onClick={save}><Save size={16} /> {saveMutation.isPending ? "A guardar..." : "Guardar cupom"}</Button></div></div></div>}
  </section>;
}
